services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    restart: no
    volumes:
      - "./mc-data:/data"
    environment:
      EULA: "TRUE"

      VERSION: "1.21"
      TYPE: "PURPUR"

      MEMORY: 2G
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 50

      OPS: "WindMagi,Twenty_Faces"

      MOTD: "Test Server"

      LEVEL: world
